services:
  postgres:
    user: root
    image: postgres:15.6
    env_file:
      - .env
    ports:
      - "5432:5432"

  airflow-webserver:
    user: root
    image: apache/airflow:2.10.2-python3.10
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./my_venv:/my_venv
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --lastname Lavrov --firstname Artem --role Admin --email email@example.com --password 4322 &&
               airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.10.2-python3.10
    depends_on:
      - airflow-webserver
      - postgres
    env_file:
      - .env

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./my_venv:/my_venv
    command: airflow scheduler
